---
title: Interpreter
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Expression {
        class IExpression {
            <<interface>>
            +interpret() string
        }
        class LiteralStringExpression {
            +LiteralStringExpression(literalString: string)
            +interpret() string
        }
        class MultiplyExpression {
            -left: IExpression
            -right: IExpression
            +MultiplyExpression(left: IExpression, right: IExpression)
            +interpret() string
        }
        class NumberExpression {
            +Number(number: int)
            +interpret() string
        }
    }
    class Client

    IExpression <|.. LiteralStringExpression
    IExpression <|.. MultiplyExpression
    IExpression <|.. NumberExpression
    Client --> IExpression : uses
    %% Miscs
    MultiplyExpression o--> IExpression : has multiple

    %% Notes
    note for MultiplyExpression "NonTerminalExpression"
    note for NumberExpression "TerminalExpression"
    note for IExpression "This expression: LiteralString * (Number | LiteralString)"
    note for Context "Context contains info that's global to this interpreter. (Context is not used in this example.)"
    note "Goal: Turns a language's grammar rules into classes, so you can parse & evaluate expressions step-by-step"
