---
title: Iterator
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
    namespace Aggregate {
        class IAggregate {
            <<interface>>
            +createIterator() IIterator
        }
        class MemeCollection {
            -memes: List~Meme~
            +add(meme: Meme)
            +count() int
            +pop(index: int) Meme
            +createIterator() MemeIterator
        }
    }
    namespace Iterator {
        class IIterator {
            <<interface>>
            +first()
            +isDone() bool
            +currentItem()
            +next()
        }
        class MemeIterator {
            -memes: List~Meme~
            +first() Meme
            +currentItem() Meme
            +next() Meme
        }
    }
    class Client
    class Meme

    IAggregate <|.. MemeCollection
    IIterator <|.. MemeIterator
    Client --> IIterator: uses
    Client --> IAggregate: uses
    %% Miscs
    MemeIterator --> MemeCollection: uses
    MemeCollection ..> MemeIterator: creates

    %% Notes
    note for IAggregate "Aggregate(Collection): Is the collection itself"
    note for IIterator "Iterator: Controls how aggregate is iterated"
    note for MemeCollection "createIterator(): return MemeIterator(this)"
    note "Goal: Provide a custom way to traverse a collection without exposing what data structure is used"