---
title: Observer
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Subject {
        class ISubject {
            <<interface>>
            +attach(observer: IObserver)
            +detach(observer: IObserver)
            +notify()
        }
        class Pacman {
            -observers: List~IObserver~
            -pacState: PacState
            +getState() PacState
            +setState(newState: PacState)
        }
    }
    namespace Observer {
        class IObserver {
            <<interface>>
            +update(pacman: ISubject)
        }
        class Ghost {
            -color: string
            -subjectState: PacState
            +update(pacman: Pacman)
        }
    }
    class PacState {
        <<enumeration>>
        CHOMP
        DEAD
        POWER_UP
    }

    ISubject <|.. Pacman
    IObserver <|.. Ghost
    %% Miscs
    Ghost ..> Pacman : uses
    ISubject o--> IObserver : has many

    %% Notes
    note for ISubject "notify(): for all observers\n o->update(this)"
    note for Pacman "setState(pacstate): this->pacstate = pacstate\n this->notify()"
    note for Ghost "[optional]update(subject): this->observerState = subject->getState()"
    note "Goal: Lets 1 object automatically notify a group of other objects whenever its state changes."