---
title: State
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace State {
        class IState {
            <<interface>>
            +turnOn(phone: Phone)
            +turnOff(phone: Phone)
            +toggleLock(phone: Phone)
            +call(phone: Phone)
        }
        class OnState {
            +turnOn(phone: Phone)
            +turnOff(phone: Phone)
            +toggleLock(phone: Phone)
            +call(phone: Phone)
        }
        class OffState {
            +turnOn(phone: Phone)
            +turnOff(phone: Phone)
            +toggleLock(phone: Phone)
            +call(phone: Phone)
        }
        class UnlockedState {
            +turnOn(phone: Phone)
            +turnOff(phone: Phone)
            +toggleLock(phone: Phone)
            +call(phone: Phone)
        }
        class LockedState {
            +turnOn(phone: Phone)
            +turnOff(phone: Phone)
            +toggleLock(phone: Phone)
            +call(phone: Phone)
        }
    }
    namespace Context {
        class Phone {
            -state: IState
            +turnOn()
            +turnOff()
            +toggleLock()
            +call()
            +setState(newState: IState)
        }
    }

    IState <|.. OnState
    IState <|.. OffState
    IState <|.. LockedState
    IState <|.. UnlockedState
    %% Misc
    Phone o--> IState : has a
    IState ..> Phone : uses

    %% Notes
    note for Phone "turnOn(): state->turnOn(this)"
    note "Goal: Lets an object change its behavior when its internal state changes."