---
title: Template Method
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
    namespace AbstractClass {
        class Pizza {
            <<abstract>>
            +prepareFood()
            #kneadDough()
            #spreadSauce()
            #addCheese()
            #addCondiments()
            #sprinkleToppings()
            #bake()
        }
    }
    namespace ConcreteClass {
        class DeepDish {
            +prepareFood()
            #kneadDough()
            #spreadSauce()
            #addCheese()
            #addCondiments()
            #sprinkleToppings()
            #bake()
        }
    }

    Pizza <|-- DeepDish

    %% Notes
    note "Goal: Defines the overall steps of an algorithm in a base class, but lets subclasses provide their own implementations for some of those steps."