---
title: Visitor
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
    namespace Visitor {
        class IVisitor {
            <<interface>>
            +visitLiquor(liquor: Liquor)
            +visitNecessity(necessity: Necessity)
            +visitTobacco(tobacco: Tobacco)
        }
        class TaxVisitor {
            +visitLiquor(liquor: Liquor)
            +visitNecessity(necessity: Necessity)
            +visitTobacco(tobacco: Tobacco)
        }
    }
    namespace Element {
        class IElement {
            <<interface>>
            +accept(visitor: IVisitor)
        }
        class Liquor {
            +accept(visitor: IVisitor)
        }
        class Necessity {
            +accept(visitor: IVisitor)
        }
        class Tobacco {
            +accept(visitor: IVisitor)
        }
    }
    class Client

    IVisitor <|.. TaxVisitor
    IElement <|.. Liquor
    IElement <|.. Necessity
    IElement <|.. Tobacco
    Client ..> IVisitor
    Client ..> IElement
    %% Miscs
    IVisitor ..> Liquor : uses
    IVisitor ..> Necessity : uses
    IVisitor ..> Tobacco : uses
    IElement ..> IVisitor : uses

    %% Notes
    note "Goal: Add new methods to objects without changing their classes."
    note "Good: Easy to add new operations(methods). Just add a new IVisitor"
    note "Bad: Hard to add new elements. If add new IElement, every visitor must be updated!"