---
title: Class Adapter
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Target {
        %% Target
        class IBubblegum {
            <<interface>>
            +chew()
        }
    }
    namespace Adaptee {
        %% Adaptee
        class Ship {
            +cruise()
        }
    }
    namespace Adapter {
        %% Adapter
        class BubblegumShipAdapter {
            +chew()
        }
    }

    IBubblegum <|.. BubblegumShipAdapter
    Ship <|-- BubblegumShipAdapter : extends
    %% Client
    Client --> IBubblegum : uses

    %% Notes
    note for BubblegumShipAdapter "chew(): this->cruise()"
    note "Goal: Allows incompatible interfaces to work together."
    note "Class Adapter uses inheritance to make them compatible"
    note "Target: The interface the Client uses"
    note "Adaptee: The class with useful functionality, but an incompatible interface"
    note "Adapter: Lets you use an Adaptee as if it were a Target"