---
title: Bridge
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
	namespace Abstraction {
		%% Abstraction
		class Door {
			<<abstract>>
			-impl: IMaterial
			+applyMaterial()
		}
		class RevolvingDoor
		class DutchDoor
		class RollerDoor
	}
    namespace Implementation {
        %% Implementation
        class IMaterial {
            <<interface>>
            +implementMaterial()
        }
        class Glass
        class Wood
        class Steel
    }

    Door <|.. RevolvingDoor
    Door <|.. DutchDoor
    Door <|.. RollerDoor
    IMaterial <|.. Glass
    IMaterial <|.. Wood
    IMaterial <|.. Steel
    %% Client
    Client --> Door : uses
    %% Misc
    Door x--> IMaterial : owns a

    %% Notes
    note for Door "applyMaterial(): impl->implementMaterial()"
    note "Goal: Lets different abstractions be paired with different implementations, so both can evolve independently"
    note "Abstraction: What the client sees & uses"
    note "Implementation: defines how it's done"
    note "Tip: If you suffer a 'class explosion', use this pattern!"
