---
title: Flyweight (Context) 
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
	namespace Flyweight {
		%% SharedFlyweight
		class IInsectType {
			<<interface>>
			+move(context:InsectContext)
		}
		class InsectType {
			-name: string
			-color: string
			-canMetamorphosize: bool
			+move(context:InsectContext)
		}
		%% UnsharedFlyweight
		class SpecialInsectType {
			-canExplode: bool
			-scentificName: string
			+move(context:InsectContext)
		}
	}
	namespace FlyweightFactory {
		%% FlyweightFactory
		class InsectTypeFactory {
			-insectTypes: Map~string,IInsectType~
			+getInsectType(name: string, color: string, canMetamorphosize: bool) InsectType
		}
	}
    namespace Context {
		%% Context
		class InsectContext {
			-position: Vector
			+setPosition(vector: Vector)
		}
	}
    %% Client
    class Client {
        insectFactory: InsectFactoryType
    }

	IInsectType <|.. InsectType
    IInsectType <|.. SpecialInsectType
    %% Miscs.
    InsectTypeFactory o--> IInsectType : has many
    InsectContext o--> IInsectType : has a
    Client --> InsectContext : uses
    InsectContext --> InsectTypeFactory : uses
    
    %% Notes
    note for InsectTypeFactory "getInsectType(): string key = name + _ + color + _ + canMetamorphosize\nMap.getAndAddIfNotExist(key,new InsectType(...))"
    note for InsectTypeFactory "Only creates SharedFlyweights, NOT Unshared ones"
    note "Goal: Minimize memory usage by sharing intrinsic states across similar objects, and keeping extrinsic states outside and supplied by the client/context."
    note "Intrinsic state: shared, immutable, heavy data"
    note "Extrinsic state: unique, mutable, lightweight data"
    note "Context: Holds extrinsic states. Can be made mutable/immutable"
    note "You can create classes that doesn't share. 'SpecialInsectType'"