---
title: Flyweight (Client) 
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
	
    
	namespace Flyweight {
		%% SharedFlyweight
		class IInsectType {
			<<interface>>
			+move(position: Vector, newPosition: Vector)
		}
		class InsectType {
			-name: string
			-color: string
			-canMetamorphosize: bool
			+move(position: Vector, newPosition: Vector)
		}
		%% UnsharedFlyweight
		class SpecialInsectType {
			-canExplode: bool
			-scentificName: string
			+move(position: Vector, newPosition: Vector)
		}
	}
	namespace FlyweightFactory {
		%% FlyweightFactory
		class InsectTypeFactory {
			-insects: Map~string, IInsectType~
			+getInsectType(name: string, color: string, canMetamorphosize: bool) InsectType
		}
	}
	%% Client
    class Client {
        -insectFactory: InsectTypeFactory
    }
	
	
    IInsectType <|.. InsectType
    IInsectType <|.. SpecialInsectType
    Client --> IInsectType : uses
    Client --> InsectTypeFactory : uses
    %% Miscs. 
    InsectTypeFactory o--> IInsectType : has many
    
    %% Notes
    note for InsectTypeFactory "getInsectType(): string key = name + _ + color + _ + canMetamorphosize\nMap.getAndAddIfNotExist(key,new InsectType(...))"
    note for InsectTypeFactory "Only creates SharedFlyweights, NOT Unshared ones"
	note "Goal: Minimize memory usage by sharing intrinsic states across similar objects, and keeping extrinsic states outside and supplied by the client/context."
    note "Intrinsic state: shared, immutable, heavy data"
    note "Extrinsic state: unique, mutable, lightweight data"
    note "You can create classes that doesn't share. 'SpecialInsectType'"