---
title: Chain of Responsibility
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Handler {
        class IReceiver {
            <<interface>>
            +handleRequest(request: string)
        }
        class Receiver {
            <<abstract>>
            #nextReceiver: IReceiver
            +handleRequest(request: string)*
        }
        class Doctor {
            +handleRequest(request: string)
        }
        class Lawyer {
            +handleRequest(request: string)
        }
        class FireFighter {
            +handleRequest(request: string)
        }
        class Artist {
            +handleRequest(request: string)
        }
    }
    class Client

    IReceiver <|.. Receiver
    Receiver <|-- Doctor
    Receiver <|-- Lawyer
    Receiver <|-- Artist
    Client --> IReceiver : uses
    %% Miscs
    IReceiver o--> IReceiver : has a

    %% Notes
    note for Artist "handleRequest(): if can handle request. handle it, otherwise pass to next handler"
    note "Lets you send a request along a chain of handlers/receivers"