---
title: Command
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Receiver {
        class Light {
            +toggleLightState(isOn: bool)
            +alterLightColor(color: string)
        }
    }
    namespace Command {
        class ICommand {
            <<interface>>
            +execute()
        }
        class LightCommand {
            <<abstract>>
            light: Light
            +execute()*
        }
        class LightOnCommand {
            +execute()
        }
        class LightOffCommand {
            +execute()
        }
        class LightColorChangeCommand {
            +LightColorChange(light: Light, color: string)
            +execute()
        }
    }
    namespace Invoker {
       class RemoteControl {
           command: ICommand
           setCommand(command: ICommand)
       }
    }
    class Client

    ICommand <|.. LightCommand
    LightCommand <|-- LightOnCommand
    LightCommand <|-- LightOffCommand
    LightCommand <|-- LightColorChangeCommand
    Client --> Light : sets
    Client ..> ICommand : creates
    %% Miscs
    LightCommand o--> Light : has a
    RemoteControl o--> ICommand : has a

   %% Notes
   note for LightCommand "execute(): light->Operation()"
   note "Goal: Turns a request/action into an object. Can also undo commands."