---
title: Builder
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Product {
        %% Products
        class IHumanoid {
            <<interface>>
            +setHead(string head)
            +setTorso(string torso)
            +setArms(string arms)
            +setLegs(string legs)
            +setFeet(string feet)
        }
        class Humanoid {
            <<abstract>>
            #head: string
            #torso: string
            #arms: string
            #legs: string
            #feet: string
            +getHead() string
            +getTorso() string
            +getArms() string
            +getLegs() string
            +getFeet() string
        }
        class Robot
        class Smurf
    }

    namespace Builder {
        %% Builders
        class IHumanoidBuilder {
            <<interface>>
            +reset()
            +buildHead()
            +buildTorso()
            +buildArms()
            +buildLegs()
            +getResult() Humanoid
        }
        class HumanoidBuilder {
            <<abstract>>
            #humanoid: IHumanoid
        }
        class RobotBuilder {
            +getResult() Robot
        }
        class SmurfBuilder {
            +getResult() Smurf
        }
    }
    namespace Director {
        %% Director
        class DirectorTypeA {
            +makeTinMan(builder IHumanoidBuilder) Robot
            +makeGrandpaSmurf(builder IHumanoidBuilder) Smurf
        }
        class DirectorTypeB {
            -builder: IHumanoidBuilder
            +construct(type string) : Humanoid
            +changeBuilder(builder IHumanoidBuilder)
        }
    }

    IHumanoid <|.. Humanoid
    Humanoid <|-- Robot
    Humanoid <|-- Smurf
    IHumanoidBuilder <|.. HumanoidBuilder
    HumanoidBuilder <|-- RobotBuilder
    HumanoidBuilder <|-- SmurfBuilder
    DirectorTypeA ..> IHumanoidBuilder : uses
    DirectorTypeB ..> IHumanoidBuilder : uses
    %% Misc.
    RobotBuilder ..> Robot : "creates"
    SmurfBuilder ..> Smurf : "creates"

    %% Notes
    note "Directors tells how an object should be assembled"
    note "Goal: Separate the assembly of an object from its creation (creating its individual parts)."