---
title: Factory Method
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    namespace Creator {
        %% Creator
        class IFarm {
            <<interface>>
            +testProduct()
            +createProduct() IProduct
        }
        class AlmondOrchard {
            +createProduct() Almond
        }
        class DairyFarm {
            +createProduct() Milk
        }
    }
    namespace Product {
        %% Product
        class IProduct {
            <<interface>>
        }
        class Milk
        class Almond
    }

    IFarm <|.. AlmondOrchard
    IFarm <|.. DairyFarm
    %% Product
    IProduct <|.. Milk
    IProduct <|.. Almond
    %% Miscs
    IFarm ..> IProduct : creates

    %% Notes
    note for IFarm "createProduct(): return new IProduct(); #Factory method"
    note for IFarm "testProduct(): product = createProduct();\ndo some stuff with the product..."
    note "Let subclasses decide what class to create using a method"  