---
title: Singleton
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
    %% Singleton
    class Singleton {
        -instance: Singleton$
        -Singleton()
        +getInstance() Singleton$
    }

    %% Notes
    note for Singleton "Constructor must be private"
    note for Singleton "getInstance(): if instance is null\ninstance = new Singleton()\nreturn instance"
    note "Goal: Ensure a class only has 1 instance & provide global access to it."