---
title: Composite
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
	namespace Component {
		%% Component
		class ICandy {
			<<interface>>
			+add(candy: ICandy)
			+remove(candy: ICandy)
			+getCandy(index: int) ICandy
			+make()
		}
	}
	namespace Leaf {
		%% Leaf
		class JawBreaker {
			+make()
		}
		class Gum {
			+make()
		}
		class ChocolateBar {
			+make()
		}
	}
	namespace Composite {
		%% Composite
		class CandyBag {
			#candies List~ICandy~
			+add(candy: ICandy)
			+remove(candy: ICandy)
			+getCandy(index: int) ICandy
			+make()
		}
	}
	
    ICandy <|.. JawBreaker
    ICandy <|.. ChocolateBar
    ICandy <|.. Gum
    ICandy <|.. CandyBag
	%% Client
	Client --> ICandy
    %% Misc
    CandyBag o--> ICandy : has many

    %% Notes
    note "Goal: Treat individual and group of objects uniformly"
    note for CandyBag "make(): loop c in candies\n g->make()"
  