---
title: Decorator
config:
    class:
        hideEmptyMembersBox: true
---
classDiagram
	namespace Component {
		%% Component
		class ISpecies {
			<<interface>>
			+fight()
		}
	}
	namespace Decorator {
		%% Decorator
		class BuffDecorator {
			<<abstract>>
			#species: ISpecies
			+fight()*
		}
		class MagicResist {
			+fight()
		}
		class DoubleExp {
			+fight()
		}
	}
    
    ISpecies <|.. Human
    ISpecies <|.. Orc
    ISpecies <|.. BuffDecorator
    BuffDecorator <|-- MagicResist
    BuffDecorator <|-- DoubleExp
    %% Client
    Client --> ISpecies
	%% Miscs
	BuffDecorator o--> ISpecies : has a
	
    %% Notes
    note for DoubleExp "fight(): species->fight();"
    note "Goal: Dynamically add new features to an object without changing its original code, by wrapping it."
    